// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Mon Dec 23 02:17:00 2024

clock_top_57 clock_top_57_inst
(
	.clk_50m_57(clk_50m_57_sig) ,	// input  clk_50m_57_sig
	.rst_57(rst_57_sig) ,	// input  rst_57_sig
	.sw_57(sw_57_sig) ,	// input [7:0] sw_57_sig
	.key_57(key_57_sig) ,	// input [7:0] key_57_sig
	.seg_57(seg_57_sig) ,	// output [6:0] seg_57_sig
	.dig_57(dig_57_sig) ,	// output [7:0] dig_57_sig
	.led_57(led_57_sig) ,	// output [7:0] led_57_sig
	.bell_57(bell_57_sig) 	// output  bell_57_sig
);

